/**
 * Único sitio donde se nombran los canales IPC. Main y preload importan de
 * aquí, así que un canal mal escrito es un error de compilación y no un
 * `invoke` que se queda colgado para siempre.
 */
export const IPC_CHANNELS = {
  settingsGet: 'settings:get',
  settingsSet: 'settings:set',
  savesList: 'saves:list',
  savesCreate: 'saves:create',
  savesLoad: 'saves:load',
  savesDelete: 'saves:delete',
  teamsList: 'teams:list',
  teamsGet: 'teams:get',
  teamsListCatalog: 'teams:listCatalog',
  teamsListLeagues: 'teams:listLeagues',
  teamsListScope: 'teams:listScope',
  // Ficha de cualquier club (fase 5).
  teamsGetProfile: 'teams:getProfile',
  playersListByTeam: 'players:listByTeam',
  playersGet: 'players:get',
  gameStateGet: 'gameState:get',
  gameStateSetManagerNationality: 'gameState:setManagerNationality',
  seasonGetCurrent: 'season:getCurrent',
  seasonGetStandings: 'season:getStandings',
  seasonListLeagues: 'season:listLeagues',
  seasonListFixtures: 'season:listFixtures',
  seasonListTeamFixtures: 'season:listTeamFixtures',
  seasonGetNextGame: 'season:getNextGame',
  seasonAdvanceDay: 'season:advanceDay',
  seasonAdvanceToNextGame: 'season:advanceToNextGame',
  seasonGetPlayoffs: 'season:getPlayoffs',
  seasonGetCup: 'season:getCup',
  seasonListContinental: 'season:listContinental',
  seasonGetContinental: 'season:getContinental',
  seasonStartNext: 'season:startNext',
  // Calendario mensual (fase 5).
  calendarGetMonth: 'calendar:getMonth',
  // Entrenadores y ranking (fase 5).
  coachesRanking: 'coaches:ranking',
  coachesGetProfile: 'coaches:getProfile',
  rotationGet: 'rotation:get',
  rotationSave: 'rotation:save',
  rotationAuto: 'rotation:auto',
  tacticsGet: 'tactics:get',
  tacticsSave: 'tactics:save',
  statsTeamSeason: 'stats:teamSeason',
  statsLeaders: 'stats:leaders',
  trainingGetPlan: 'training:getPlan',
  trainingSavePlan: 'training:savePlan',
  clubGetFinances: 'club:getFinances',
  clubSetTicketPrice: 'club:setTicketPrice',
  clubExpandArena: 'club:expandArena',
  clubGetBoard: 'club:getBoard',
  staffGet: 'staff:get',
  staffHire: 'staff:hire',
  staffFire: 'staff:fire',
  youthGet: 'youth:get',
  youthPromote: 'youth:promote',
  youthUpgrade: 'youth:upgrade',
  marketGetStatus: 'market:getStatus',
  marketSearch: 'market:search',
  marketOffer: 'market:offer',
  marketListContracts: 'market:listContracts',
  marketRenew: 'market:renew',
  marketRelease: 'market:release',
  marketListLoans: 'market:listLoans',
  marketLoanOut: 'market:loanOut',
  marketLoanIn: 'market:loanIn',
  matchStart: 'match:start',
  matchAdvancePeriod: 'match:advancePeriod',
  matchGet: 'match:get',
  matchSnapshot: 'match:snapshot',
  matchAdvancePossession: 'match:advancePossession',
  matchSubstitute: 'match:substitute',
  matchTimeout: 'match:timeout',
  matchLiveTactics: 'match:liveTactics',
  matchAutoRotation: 'match:autoRotation',
  matchPreview: 'match:preview',
  matchRoundResults: 'match:roundResults',
  historyGet: 'history:get',
  careerGetStatus: 'career:getStatus',
  careerAccept: 'career:accept',
  careerResign: 'career:resign',
  careerWait: 'career:wait',
  careerAcceptNational: 'career:acceptNational',
  careerLeaveNational: 'career:leaveNational',
  nationalGetOverview: 'national:getOverview',
  draftGet: 'draft:get',
  draftSimulateToUser: 'draft:simulateToUser',
  draftPick: 'draft:pick',
  draftPass: 'draft:pass',
  draftSimulateAll: 'draft:simulateAll',
  nationalGetCallup: 'national:getCallup',
  nationalSaveCallup: 'national:saveCallup',
  updatesGet: 'updates:get',
  updatesCheck: 'updates:check',
  updatesInstall: 'updates:install',
  /** Del proceso principal a la ventana: el estado de la actualización ha cambiado. */
  updatesChanged: 'updates:changed',
  editorOverview: 'editor:overview',
  editorTeam: 'editor:team',
  editorUpdateTeam: 'editor:updateTeam',
  editorUpdatePlayer: 'editor:updatePlayer',
  editorMovePlayer: 'editor:movePlayer',
  editorResetTeam: 'editor:resetTeam',
  editorResetAll: 'editor:resetAll',
  inboxGet: 'inbox:get',
  inboxUnreadCount: 'inbox:unreadCount',
  inboxMarkRead: 'inbox:markRead',
  inboxMarkAllRead: 'inbox:markAllRead',
  inboxGetPress: 'inbox:getPress',
  inboxAnswerPress: 'inbox:answerPress'
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
