/**
 * Único sitio donde se nombran los canales IPC. Main y preload importan de
 * aquí, así que un canal mal escrito es un error de compilación y no un
 * `invoke` que se queda colgado para siempre.
 */
export const IPC_CHANNELS = {
  settingsGet: 'settings:get',
  settingsSet: 'settings:set',
  savesList: 'saves:list',
  savesCreate: 'saves:create',
  savesLoad: 'saves:load',
  savesDelete: 'saves:delete',
  teamsList: 'teams:list',
  teamsGet: 'teams:get',
  teamsListCatalog: 'teams:listCatalog',
  teamsListLeagues: 'teams:listLeagues',
  playersListByTeam: 'players:listByTeam',
  playersGet: 'players:get',
  gameStateGet: 'gameState:get',
  seasonGetCurrent: 'season:getCurrent',
  seasonGetStandings: 'season:getStandings',
  seasonListLeagues: 'season:listLeagues',
  seasonListFixtures: 'season:listFixtures',
  seasonListTeamFixtures: 'season:listTeamFixtures',
  seasonGetNextGame: 'season:getNextGame',
  seasonAdvanceDay: 'season:advanceDay',
  seasonAdvanceToNextGame: 'season:advanceToNextGame',
  seasonGetPlayoffs: 'season:getPlayoffs',
  seasonGetCup: 'season:getCup',
  seasonListContinental: 'season:listContinental',
  seasonGetContinental: 'season:getContinental',
  seasonStartNext: 'season:startNext',
  rotationGet: 'rotation:get',
  rotationSave: 'rotation:save',
  rotationAuto: 'rotation:auto',
  tacticsGet: 'tactics:get',
  tacticsSave: 'tactics:save',
  statsTeamSeason: 'stats:teamSeason',
  statsLeaders: 'stats:leaders',
  trainingGetPlan: 'training:getPlan',
  trainingSavePlan: 'training:savePlan',
  clubGetFinances: 'club:getFinances',
  clubSetTicketPrice: 'club:setTicketPrice',
  clubExpandArena: 'club:expandArena',
  clubGetBoard: 'club:getBoard',
  staffGet: 'staff:get',
  staffHire: 'staff:hire',
  staffFire: 'staff:fire',
  youthGet: 'youth:get',
  youthPromote: 'youth:promote',
  youthUpgrade: 'youth:upgrade',
  marketGetStatus: 'market:getStatus',
  marketSearch: 'market:search',
  marketOffer: 'market:offer',
  marketListContracts: 'market:listContracts',
  marketRenew: 'market:renew',
  marketRelease: 'market:release',
  marketListLoans: 'market:listLoans',
  marketLoanOut: 'market:loanOut',
  marketLoanIn: 'market:loanIn',
  matchStart: 'match:start',
  matchAdvancePeriod: 'match:advancePeriod',
  matchGet: 'match:get'
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
